development:
  adapter: postgresql
  encoding: unicode
  database: project3_dev
  pool: 5
  username: rails
  password: rail

test:
  adapter: postgresql
  encoding: unicode
  database: project3_test
  pool: 5
  username: rails
  password: rail

production:
  adapter: postgresql
  encoding: unicode
  database: project3_production
  pool: 5
  username: rails
  password: rail